/********************************
*								*
*			cell.cg				*
*		cell shader				*
*								*
********************************/

void main(in float4 position :POSITION, 
          in float4 color : COLOR, 
		  in float3 lightPos[10],
		  in float3 lightColor,
		  in int numLights,
		  out float4 outColor : COLOR0,  
		  out float4 outPos : POSITION0,
		  const uniform float4x4 modelViewProjMatrix)
{
	outColor.rg = color.rg;
	outColor.b = 1;	
}
